### PR TITLE
adjusting to Rox SDK v5

### PR DESCRIPTION
**Pull request by AsafRollout**
update internally
will open a PR from master to the DefinitelyTyped repository if that makes sense..

### CODE REVIEW

**Review by lilienblum — APPROVED** [review]

**Comment by lilienblum** [comment]
Maybe we should include this into roxjs repo?

**Comment by AsafRollout** [comment]
i don't know much about TS
GG decided to go with this public repository
but all common libraries are there..

**Comment by AsafRollout** [comment]
if it should change, maybe talk with @tkammer  about it
and open a separate ticket

**Comment by AsafRollout** [comment]
@dn-l 
does the definitions looks ok?
again, never wrote in TS until now

i did created an app to test it, and it worked...

**Comment by lilienblum** [comment]
Yes looks fine

**Pull request merged**
